### ISSUE TITLE
Update "Contact Us" email address

### ISSUE THREAD

**Issue by dgkf** [pharmaR/pharmaR.github.io#104]
Contact emails are still going to PSI AIMS and pestering Lyn

We have these two sub-groups in our mailing list that might be better alternatives:

![image](https://github.com/pharmaR/pharmaR.github.io/assets/18220321/78f54ebf-5760-4c61-8497-a533d0fd93be)

**Comment by jcabercrombie** [comment]
Issue addressed in #119. Closing this issue.
