### ISSUE TITLE
Webpage not available

### ISSUE THREAD

**Issue by llrs** [pharmaR/pharmaR.github.io#40]
Hi,

Not sure what is this organization about I was expecting to find the webpage and learn more at [pharmaR.github.io](https://pharmaR.github.io) but the webpage is not available. Not sure if this is the repo of [parhamaR](https://www.pharmar.org/) or what.

Thanks for riskmetric

**Comment by jmanitz** [comment]
@llrs thanks for reaching out. I am sorry that you experiencing these issues, but I cannot reproduce them: https://www.pharmaR.org/. If you continue to have availability issues, please reach out again.
